language: ruby
rvm:
- 2.2
before_script:
- mysql -e 'create database battleship_test;'
env:
  global:
  - secure: EvzBM0EnWn5vApGk+XHsfNbXawfbZWRrstURls7v6gvwSOEwCVo3ByhXb78IEcv6cgWwx65wsbVRU0GI2M7a4uM3N+s/UtoWKVr//Cdomas4IbLZMbqgFBh+k8pdCy7ptreupuVOhT5bh+Ii7hfEBsDK7W3K4XUTRxrjcki+LVvnOJUfGAlleSF7LTHgW6RyS1mT5s/EJxpm191f6QypoLMrdpaZRVPrem4LGam6N1dXmySDuD4N6drNPXINZboTrJ0vm7KpV10vBMF3XDFbGIhNr0gjFG583ZTFkYG5pPCboTlwtBRehstkuV2c+Yo50dFQF/jrGOBQP8kxOYytZdUjHNHBC/BCJ89659xn67V5pBlqZfS55Ksjb4gSUIb16vPhNxaTxzBXrY/uSTJGkqxXc5uJd81hKzKt2YZc7pYYQNqYaIQbMKOUz+KRkkdrwBkRq9MTB/HjbGYAY7izbHdDFbSkXAx3ISuHtMEUUfzN3iFy6BMs1PwWfSHJpoOSs9y2dLuaQ/Sfsx7NOY8kdRBqVQnwn7SFAzV16DZD2jjgp1qcXu0HkhZPqhIDlILkbjKscW5NnNVvqXEqo5CD6w08+AGedLUlCyofLwRr9/P8uz8rYH4k9wFCCW6VAkA6RwFMFp/168Dc2Xb6WaXMk1JUSdt69ZFJMXpYeOWWzDA=
